version: 2
jobs:
  build:
    working_directory: ~/caffeination_be
    docker:
      - image: circleci/ruby:3.0.0
        environment:
          PGHOST: localhost
          PGUSER: caffeination_be
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: caffeination_be
          POSTGRES_DB: caffeination_be_test
          POSTGRES_PASSWORD: POSTGRES_HOST_AUTH_METHOD=trust
    steps:
      - checkout

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rake
