---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/user_log":
    post:
      summary: Creates a User Log
      tags:
      - User Log
      parameters: []
      responses:
        '201':
          description: user_log created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
                  properties:
                    type:
                      type: string
                    event:
                      type: string
                    id:
                      type: string
                    first_name:
                      type: string
                    last_name:
                      type: string
                    user_name:
                      type: string
                    email:
                      type: string
                    zipcode:
                      type: string
              required:
              - payload
              - type
              - event
              - id
              - first_name
              - last_name
              - user_name
              - email
              - zipcode
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
